version: '3.7'
services:
  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: moodle_ripoff
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: hiking
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  admin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "80:80"
    depends_on:
      - mysql
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

#  app:
#    image: jee/jumpstart
#    ports:
#      - "8080:8080"
#      - "4848:4848"
#      - "9009:9009"
#    depends_on:
#      - mysql
#    healthcheck:
#      test: curl --fail http://localhost:8080/health/ready || exit 1
#    build:
#      context: .
#      dockerfile: Dockerfile
